site_name: Will Dean
site_description: Personal Website for Will Dean

theme: 
  name: material
  features: 
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.expand
    - navigation.top
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - tags:
      tags_file: tags.md
  - markdownextradata
  # - git-revision-date-localized: 
  #     enable_creation_date: true
  # - mkdocs-jupyter

markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.highlight: 
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra: 
  social: 
    - icon: fontawesome/brands/github
      link: https://github.com/wd60622
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/williambdean/

nav:
  - Welcome: index.md
  - Blog: 
    - blog/index.md
    - 2022: 
      - blog/posts/2022/pathlib.md
      - Pydantic for Configs: blog/posts/2022/pydantic-configs.md
      - blog/posts/2022/site-setup.md
  - Favorite Resources: 
    - resources/index.md
  - Tags: tags.md